config/routes.rb
Rails.application.routes.draw do
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	# root "articles#index"

	resources :shopping_carts, only: [:index, :edit, :update, :destroy], path: :shopping_cart

	resources :line_items, only: [:create]

	resources :orders, only: [:new, :create, :show]
	resources :products, only: [:index, :show]

	root 'root#index'
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
	belongs_to :session

	has_many :line_items, as: :owner

	validates_associated :line_items
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
	before_action :has_shopping_cart, only: %i[ update destroy ]
	before_action :set_shopping_cart, only: %i[ index update destroy ]

	# GET /shopping_carts or /shopping_carts.json
	def index
	end

	# PATCH/PUT /shopping_carts/1 or /shopping_carts/1.json
	def update
		empty = params.permit(:empty)

		if empty[:empty].present?
			@shopping_cart.destroy

			respond_to do |format|
				format.html { redirect_to shopping_carts_url, notice: "Shopping cart was emptied successfully." }
				format.json { head :no_content }
			end
		else
			line_items = shopping_cart_params.permit(line_items: [:quantity, :destroy])
			result = UpdateShoppingCart.run(shopping_cart: @shopping_cart, line_items: line_items[:line_items])

			respond_to do |format|
				if result.valid?
					format.html { redirect_to shopping_carts_url, notice: "Shopping cart was successfully updated." }
					format.json { render :index, status: :ok, location: @session.shopping_cart }
				else
					format.html { render :index, status: :unprocessable_entity }
					format.json { render json: result.errors, status: :unprocessable_entity }
				end
			end
		end
	end

	# DELETE /shopping_carts/1 or /shopping_carts/1.json
	def destroy
		@shopping_cart.destroy

		respond_to do |format|
			format.html { redirect_to shopping_carts_url, notice: "Shopping cart was successfully destroyed." }
			format.json { head :no_content }
		end
	end

	private

		# Use callbacks to share common setup or constraints between actions.
		def set_shopping_cart
			@shopping_cart = @session.shopping_cart
		end

		# Only allow a list of trusted parameters through.
		def shopping_cart_params
			params.fetch(:shopping_cart, {})
		end
end

app/views/shopping_carts/_form.html.erb
<%= form_with(model: shopping_cart, class: "contents") do |form| %>
	<%= render Form::ErrorComponent.new model: shopping_cart %>

	<% shopping_cart.line_items.each do |line_item| %>
		<%= fields_for 'shopping_cart[line_items[]]', line_item do |line| %>
			<%= render line_item, form: line %>
		<% end %>
	<% end %>

	<hr class="mt-10 mb-5" />

	<div class="sm:grid sm:grid-cols-2">
		<div class="mb-5 sm:col-span-1">
			<%= render Form::SubmitButtonComponent.new form: form, label: 'Update' %>
		</div>
		<div class="mb-5 sm:col-span-1  text-right">
			<%= render Form::SubmitButtonComponent.new form: form, name: :empty, label: 'Remove All' %>
		</div>
	</div>

	<hr class="mb-5" />
<% end %>

app/views/shopping_carts/index.html.erb
<%= render Layout::PageComponent.new title: 'Shopping Cart', alert: alert, notice: notice, session: @session do %>

	<% if @shopping_cart.present? %>
		<hr class="mb-5" />

		<div class="text-right">
			<%= render Layout::LinkComponent.new label: 'Proceed to Checkout', url: new_order_url, color: :blue, type: 'button' %>
		</div>

		<hr class="my-5 mb-10" />

		<%= render "form", shopping_cart: @shopping_cart %>
	<% else %>
		<div class="cart_empty   my-5">Your shopping cart is empty</div>

		<%= render Layout::LinkComponent.new label: 'Back to Shopping', url: products_url, color: :grey, type: 'button' %>
	<% end %>

<% end %>