config/routes.rb
Rails.application.routes.draw do
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	# root "articles#index"

	resources :shopping_carts, only: [:index, :edit, :update, :destroy], path: :shopping_cart

	resources :line_items, only: [:create]

	resources :orders, only: [:new, :create, :show]
	resources :products, only: [:index, :show]

	root 'root#index'
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	belongs_to :address

	has_many :line_items, as: :owner

	validates_associated :line_items
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :set_order, only: %i[ show ]
	before_action :set_shopping_cart, only: %i[ new, create ]

	# GET /orders/1 or /orders/1.json
	def show
		unless @order.present?
			respond_to do |format|
				format.html { redirect_to shopping_carts_url, notice: "Order not found." }
				format.json { render :show, status: :unprocessable_entity }
			end
		end
	end

	# GET /orders/new
	def new
		@order = Order.new(
			customer: @session.customer ? @session.customer : Customer.new,
			address: @session.customer&.address ? @session.customer.address : Address.new,
		)
	end

	# POST /orders or /orders.json
	def create
		create_order_params = order_params.permit(customer: [:first_name, :last_name, :email_address, :phone_number, :id], address: [:line_1, :line_2, :city, :postcode, :id])

		result = CreateOrder.run(
			session: @session,
			customer: create_order_params[:customer],
			address: create_order_params[:address])

		@order = result.result

		respond_to do |format|
			if result.valid?
				has_checked_out

				format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
				format.json { render :show, status: :created, location: @order }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @order.errors, status: :unprocessable_entity }
			end
		end
	end

	private

		def set_order
			@order = Order.where(id: params[:id], customer: @session.customer).first
		end

		def set_shopping_cart
			@shopping_cart = @session.shopping_cart
		end

		def order_params
			params.fetch(:order, {})
		end
end

app/views/orders/_form.html.erb
<%= form_with(model: order, class: "contents") do |form| %>
	<%= render Form::ErrorComponent.new model: order %>

	<div class="grid grid-rows-1 gap-10 mb-8">
		<%= render Form::ModelComponent.new record_name: 'order[customer]', model: order.customer do |customer| %>
			<%= customer.text(form: customer.form, name: :first_name) %>
			<%= customer.text(form: customer.form, name: :last_name) %>
			<%= customer.text(form: customer.form, name: :email_address) %>
			<%= customer.text(form: customer.form, name: :phone_number) %>
			<%= customer.form.hidden_field(:id, value: order.customer.id) %>
		<% end %>

		<%= render Form::ModelComponent.new record_name: 'order[address]', model: order.address do |address| %>
			<%= address.text(form: address.form, name: :line_1) %>
			<%= address.text(form: address.form, name: :line_2) %>
			<%= address.text(form: address.form, name: :city) %>
			<%= address.text(form: address.form, name: :postcode) %>
			<%= address.form.hidden_field(:id, value: order.address.id) %>
		<% end %>

		<div class="grid grid-rows gap-5">
			<hr />
			<div class="grid grid-cols-2">
				<div class="col-span">
					<%= render Layout::LinkComponent.new label: 'Back to shopping cart', url: shopping_carts_path, color: :grey, type: 'button' %>
				</div>

				<div class="col-span text-right">
					<%= render Form::SubmitButtonComponent.new form: form, label: 'Place Order' %>
				</div>
			</div>
			<hr />
		</div>
	</div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>" class="w-full">
	<div class="grid grid-rows-1 gap-5 mb-8">

		<%= render Layout::GroupComponent.new label: 'Customer' do %>
			<%= render Layout::FieldComponent.new label: 'First Name', cls: 'first_name', value: order.customer.first_name %>
			<%= render Layout::FieldComponent.new label: 'Last Name', cls: 'last_name', value: order.customer.last_name %>
			<%= render Layout::FieldComponent.new label: 'Email Address', cls: 'email_address', value: order.customer.email_address %>
			<%= render Layout::FieldComponent.new label: 'Phone Number', cls: 'phone_number', value: order.customer.phone_number %>
		<% end %>

		<%= render Layout::GroupComponent.new label: 'Address' do %>
			<%= render Layout::FieldComponent.new label: 'Line 1', cls: 'line_1', value: order.address.line_1 %>
			<%= render Layout::FieldComponent.new label: 'Line 2', cls: 'line_2', value: order.address.line_2 %>
			<%= render Layout::FieldComponent.new label: 'City', cls: 'city', value: order.address.city %>
			<%= render Layout::FieldComponent.new label: 'Postcode', cls: 'postcode', value: order.address.postcode %>
		<% end %>

	</div>
</div>

app/views/orders/new.html.erb
<%= render Layout::PageComponent.new title: 'Checkout', alert: alert, notice: notice, session: @session do %>
	<%= render "form", order: @order %>
<% end %>

app/views/orders/show.html.erb
<%= render Layout::PageComponent.new title: 'Order Confirmation', alert: alert, notice: notice, session: @session do %>
	<%= render @order %>
<% end %>