config/routes.rb
Rails.application.routes.draw do
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	# root "articles#index"

	resources :shopping_carts, only: [:index, :edit, :update, :destroy], path: :shopping_cart

	resources :line_items, only: [:create]

	resources :orders, only: [:new, :create, :show]
	resources :products, only: [:index, :show]

	root 'root#index'
end

app/models/product.rb
class Product < ApplicationRecord
	validates :price, :name, presence: true

	has_one_attached :hero_image
	has_many :line_items, as: :owner

	validates_associated :line_items
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: %i[ show ]

	# GET /products or /products.json
	def index
		@products = Product.all
		@line_item = LineItem.new
	end

	# GET /products/1 or /products/1.json
	def show
		@line_item = LineItem.new
	end

	private
		
		def set_product
			@product = Product.find(params[:id])
		end

		# Only allow a list of trusted parameters through.
		def product_params
			params.require(:product).permit(:name, :price, :premium, :description)
		end
end

app/views/products/_product.html.erb
<% if defined?(type) && type == :list %>
	<%= render Shopping::ProductListingComponent.new product: product, line_item: @line_item %>
<% else %>
	<%= render Shopping::ProductDetailedComponent.new product: product, line_item: @line_item %>
<% end %>

app/views/products/index.html.erb
<%= render Layout::PageComponent.new title: 'Products', alert: alert, notice: notice, session: @session do %>
	<div id="products" class="min-w-full grid grid-rows-1 gap-5">
		<%= render @products, type: :list %>
	</div>
<% end %>

app/views/products/show.html.erb
<%= render Layout::PageComponent.new title: 'Product', alert: alert, notice: notice, session: @session do %>

	<%= render @product %>

	<%= render Layout::LinkComponent.new label: 'Back to products', url: products_path, color: :grey, type: 'button' %>
<% end %>>